name: Build and Deploy Vite to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Step 3: Install dependencies
    - run: npm ci

    # Step 4: Run tests
    - run: npm test

    # Step 5: Build the project
    - run: npm run build

    # Step 6: Upload build artifacts
    - name: Upload production-ready site to artifact storage
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: dist # Replace with your build output folder if different

  deploy:
    runs-on: ubuntu-latest
    needs: build # Ensure this job runs after 'build'

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4

    # Step 2: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        branch: gh-pages
        folder: dist # Replace with your build output folder if different
